# Generated by Django 6.0.6 on 2026-06-14 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LegalForgeAI', '0001_enable_pgvector'),
    ]

    operations = [
    ]
